### ISSUE TITLE
Are generics possible?

### ISSUE THREAD

**Issue by cozyGalvinism** [chinedufn/swift-bridge#40]
I have the following struct type defined currently `APIResponseObject<T, MT>`, where both T and MT are supposed to be deserialized by Rust.

For some reason, if I try to extern them, I get a weird error, probably because generics (e.g. `MyStruct<T>`) aren't implemented for the bridge yet?

Following code is my bridge:
```rust
#[swift_bridge::bridge]
mod ffi {
    // inferred from https://chinedufn.github.io/swift-bridge/bridge-module/opaque-types/index.html
    extern "Rust" {
        type APIResponseList<T, MT>;
        type PteroClientServer;
        type APIResponsePaginationMetaData;
        type APIResponseObject<T, MT>;
    }

    extern "Rust" {
        type PteroClient;

        #[swift_bridge(init)]
        fn new(base_url: String, api_key: String) -> PteroClient;

        // inferred from https://github.com/chinedufn/swift-bridge/blob/ecc6704985ea260ae502d7ccdd776602e5f263ea/examples/async-functions/src/lib.rs
        async fn get_servers(&self) -> Option<APIResponseList<APIResponseObject<PteroClientServer, APIResponsePaginationMetaData>, APIResponsePaginationMetaData>>;
    }
}
```

The error I receive:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,`")', /home/cozygalvinism/.cargo/registry/src/github.com-1ecc6299db9ec823/swift-bridge-ir-0.1.29/src/bridged_type.rs:335:82
```

Am I doing something wrong or is my assumption correct?

**Comment by chinedufn** [comment]
You're right that the issue is because we don't currently support generics.

---

Would something like this meet your needs for now?

```rust
type MyApiResponse = APIResponseList<
    APIResponseObject<PteroClientServer, APIResponsePaginationMetaData>,
    APIResponsePaginationMetaData,
>;

#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type MyApiResponse;
    }

    extern "Rust" {
        type PteroClient;

        #[swift_bridge(init)]
        fn new(base_url: String, api_key: String) -> PteroClient;

        // inferred from https://github.com/chinedufn/swift-bridge/blob/ecc6704985ea260ae502d7ccdd776602e5f263ea/examples/async-functions/src/lib.rs
        async fn get_servers(&self) -> Option<MyApiResponse>;
    }
}
```

Not as flexible as generics, but could work fine in the meantime if you don't have a lot of combinations that you need to support.

**Comment by cozyGalvinism** [comment]
I actually tried that and it still didn't work. However, this may be because async also isn't working for me, like, in general. If I clone your repo, I can build the example just fine, however in my project, async just results in `thread 'main' panicked at 'not implemented', /home/cozygalvinism/.cargo/registry/src/github.com-1ecc6299db9ec823/swift-bridge-ir-0.1.29/src/bridged_type.rs:695:25`.

I spent the last few hours converting my generics to flat classes, to no avail, then I wrote a few macros that define structs twice: once with serde support and another time without with a From implementation (because I thought it could've tied into serde) but that also didn't work.

So right now, my entire code looks like:
```rust
pub struct MyAsyncClient;

impl MyAsyncClient {
    async fn run_something(&self) -> String;
}

#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type MyAsyncClient;

        async fn run_something(&self) -> String;
    }
}
```
with my Cargo.toml looking like:
```toml
[package]
name = "ptero-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "ptero_rs"
crate-type = ["staticlib"]

[dependencies]
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
swift-bridge = { version = "0.1", features = ["async"] }

[build-dependencies]
swift-bridge-build = "0.1"
```

I'm probably missing something obvious... And if so, I'm sorry for bothering you x)
